name: 'check-eslint'
on:
  pull_request:
permissions: write-all
jobs:
  ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check with eslint
        run: npm i -g pnpm && pnpm i && pnpm eslint
